"""Updated user 'is_active_account' to default False

Revision ID: 5fa0ae148c40
Revises: 6adbe272a2c0
Create Date: 2025-08-31 11:12:10.528508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa0ae148c40'
down_revision: Union[str, Sequence[str], None] = '6adbe272a2c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
