"""Add job_id to Habit model

Revision ID: 7b01fef5dbfb
Revises: 5fa0ae148c40
Create Date: 2025-09-23 20:11:14.315214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b01fef5dbfb'
down_revision: Union[str, Sequence[str], None] = '5fa0ae148c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('job_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'job_id')
    # ### end Alembic commands ###
